### PR TITLE
fix(messageListViewHelp): typo

### PR DESCRIPTION
**Pull request by JoeSchr**
hilight => hightlight

### CODE REVIEW

**Comment by ThomasHabets** [comment]
Thanks!

**Comment by JoeSchr** [comment]
No problem.

I may have a few other minor PRs, but I'm slightly confused both `Readme` in `/cmd` and `/pkg` say they are not being used due to refactoring. Which one should I use?

**Comment by ThomasHabets** [comment]
Oops, that's old news. I've deleted them now.

**Comment by ThomasHabets** [comment]
The READMEs have been deleted, that is. When something fits better as a package, it should be in `pkg/`, otherwise if it's part of the main program, it should be in `cmd/cmdg/`.

**Comment by JoeSchr** [comment]
thanks, got it!

On Thu, 28 Jan 2021 11:49:07 +0100, Thomas Habets
<notifications@github.com> said:

**Pull request merged**
