### PR TITLE
messagelist: "I" marks message as read

### PR DESCRIPTION
**Pull request by TheJoeSchr**
let's me mark a message as read without opening it first.

I would love for this to also unmark the messages in the message list (remove the "X"), but I can't get this done.

also I removed this from the source where I basically copied the logic from ("e"):
```
				if !ok {
					break
				}
```

I understand why it's in there, but in my testing, even though `ok` is false, the messages get marked as read on the gmail server. verified by re-opening `cmdg` and also refreshing gmail.com page

### CODE REVIEW

**Comment by ThomasHabets** [comment]
Sorry for the late reply. I've been thinking about this. It's definitely a feature that should be there. I think that I don't want the unmarking though. I often mark some messages and then do multiple things. Sure, most of the time those "multiple things" are "add label, archive". And archiving naturally unselects, assuming one is in the inbox.

So then the question is how to quickly unselect everything. I do think it still needs to be a separate op.

That, and the PR needs `gofmt` formatting, looks like.

**Comment by TheJoeSchr** [comment]
`lf` a TUI file explorer for consoles uses `v` (or `u`?) for unselecting everything. I would mind to have to do 2 steps for mark read and then unselecting. As you say I might want to do something else also

**Comment by TheJoeSchr** [comment]
Ps.: I'm usually not programming in go, nor did I do any kind of 101 course for it yet, so please don't hesitate to point out any errors or mistakes that are not go canonical. 

I will try to get `gofmt` working and re-submit it again.

**Comment by TheJoeSchr** [comment]
Thanks


__

Typed on a mobile, please excuse any typing mistakes or short-spokeness.

**Pull request closed without merging**
